### ISSUE TITLE
Dice Game

### ISSUE THREAD

**Issue by BobbyKJH** [Dice-game-1team/dice-game#1]
## 목적 
Dice game

## Tasks
- [x] dice game 
- [x] input 창만들기
- [x] 주사위 random 수 생성

**Comment by BobbyKJH** [comment]
> ## 목적
> Dice game
> 
> ## Tasks
- [] dice game
- [] input 창만들기
- []  주사위 random 수 생성

**Comment by BobbyKJH** [comment]
## 목적
 Dice game

 ## Tasks

 - []   dice game
 - []   input 창만들기
-  []  주사위 random 수 생성
